const products = [
    {
        id:"rs01ex",
        catagore:"paltest",
        brand:"FX",
        pName:"FX Have Plates",
        image: "./image/bulltes.png",
        stars: 4.5,
        price: 1520,
        xPrice: 1600,
    },
    {
        id:"rs02ex",
        catagore:"paltest",
        brand:"FX",
        pName:"FX Javeries",
        image: "./image/bulltes.png",
        stars: 4.2,
        price: 1320,
        xPrice: 1400,
    },
    {
        id:"rs03ex",
        catagore:"paltest",
        brand:"FX",
        pName:"FX Hanmer",
        image: "./image/bulltes.png",
        stars: 5,
        price: 1020,
        xPrice: 1200,
    },
    {
        id:"rs04ex",
        catagore:"paltest",
        brand:"FX",
        pName:"FX Have Plates",
        image: "./image/bulltes.png",
        stars: 4,
        price: 1220,
        xPrice: 1280,
    }
];